### ISSUE TITLE
登陆验证码如何破

### ISSUE THREAD

**Issue by wmnickg** [xioxu/sinaWeiboSpider#4]
登陆时需要验证码 如何破？

**Comment by xioxu** [comment]
这个我在去年写过一篇文章可以参考一下： http://blog.datafiddle.net/?p=729228
简而言之就是可以利用我提供代码中的proxyTest.js去找合适的代理，然后再爬取就可以避过验证码了。

当然， 这也是我去年的结论， 之后就一直没有搞这了， 也不知现在是否适用。

**Comment by xioxu** [comment]
当然，最不济的办法就是用网上那些验证码解码服务。
